#!/bin/sh

RCLONE_CONFIG=/config/rclone/rclone.conf

if [ -z "$REMOTE_NAME" ]; then
    echo "REMOTE_NAME is not set"
    exit 1
fi
if [ -z "$REMOTE_URL" ]; then
    echo "REMOTE_URL is not set"
    exit 1
fi
if [ -z "$REMOTE_VENDOR" ]; then
    echo "REMOTE_VENDOR is not set"
    exit 1
fi

mkdir -p "$(dirname "$RCLONE_CONFIG")"

cat <<EOF >"$RCLONE_CONFIG"
[$REMOTE_NAME]
type = webdav
url = $REMOTE_URL
vendor = $REMOTE_VENDOR
nextcloud_chunk_size = 0
EOF

# Check if --auth-proxy is part of PROXY_ARGS
if echo " $PROXY_ARGS " | grep -q ' --auth-proxy '; then
  # Auth-proxy mode for per-user access.
  # Do not pass the remote name as an argument.
  exec rclone serve s3 $PROXY_ARGS
else
  # Anonymous or single-user mode.
  # Pass the remote name as an argument.
  exec rclone serve s3 $PROXY_ARGS "$REMOTE_NAME:"
fi
